namespace InventoryService.Models;

// Demand forecast for an item at a specific facility for a given period.
// Generated by ReplenishmentServiceImpl based on last 30-day consumption averages.
// Period format: "YYYY-MM" (e.g. "2026-06")
public class Forecast
{
    public int ForecastId { get; set; }
    public int ItemId { get; set; }
    public int FacilityId { get; set; }
    public string Period { get; set; } = string.Empty;  // e.g. "2026-06"
    public int ForecastQuantity { get; set; }
    public DateTime GeneratedDate { get; set; } = DateTime.UtcNow;
}
