// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelemetryService.Data;

#nullable disable

namespace TelemetryService.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260530134842_remigs")]
    partial class remigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelemetryService.Models.SensorDevice", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SensorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<int?>("AssignedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("SensorId");

                    b.ToTable("SensorDevice", (string)null);
                });

            modelBuilder.Entity("TelemetryService.Models.TelemetryRecord", b =>
                {
                    b.Property<int>("TelemetryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TelemetryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TelemetryId"));

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsExcursion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("SensorID");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TelemetryId");

                    b.HasIndex("SensorId");

                    b.ToTable("TelemetryRecord", (string)null);
                });

            modelBuilder.Entity("TelemetryService.Models.TelemetryRecord", b =>
                {
                    b.HasOne("TelemetryService.Models.SensorDevice", "SensorDevice")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TelemetryRecord_SensorDevice");

                    b.Navigation("SensorDevice");
                });

            modelBuilder.Entity("TelemetryService.Models.SensorDevice", b =>
                {
                    b.Navigation("TelemetryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
